import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  // Wheels (20) - KG1 Forged
  {
    slug: 'kg1-forged-apex-18x9',
    name: 'KG1 Forged Apex 18x9',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Lightweight forged aluminum wheel with aggressive spoke design. Perfect for performance applications.',
    price: 899.99,
    compareAtPrice: 1199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '9"',
      offset: '+35mm',
      boltPattern: '5x120',
      centerBore: '72.6mm',
      weight: '19.2 lbs',
      finish: 'Matte Black'
    }),
    inventoryQty: 15,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-vortex-19x8-5',
    name: 'KG1 Forged Vortex 19x8.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Flow-formed construction with distinctive vortex spoke pattern. Engineered for strength and style.',
    price: 1099.99,
    compareAtPrice: 1399.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '19"',
      width: '8.5"',
      offset: '+42mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '21.8 lbs',
      finish: 'Gunmetal Gray'
    }),
    inventoryQty: 12,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-titan-20x10',
    name: 'KG1 Forged Titan 20x10',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Massive 20-inch forged wheel designed for trucks and SUVs. Maximum strength and durability.',
    price: 1299.99,
    compareAtPrice: 1699.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '20"',
      width: '10"',
      offset: '+25mm',
      boltPattern: '6x139.7',
      centerBore: '106.1mm',
      weight: '32.5 lbs',
      finish: 'Satin Bronze'
    }),
    inventoryQty: 8,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-razor-17x8',
    name: 'KG1 Forged Razor 17x8',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Sharp, angular design with lightweight construction. Ideal for track and street performance.',
    price: 749.99,
    compareAtPrice: 999.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '17"',
      width: '8"',
      offset: '+45mm',
      boltPattern: '5x100',
      centerBore: '57.1mm',
      weight: '16.8 lbs',
      finish: 'Gloss Black'
    }),
    inventoryQty: 20,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-storm-18x8-5',
    name: 'KG1 Forged Storm 18x8.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Dynamic spoke pattern inspired by storm formations. Premium forged aluminum construction.',
    price: 949.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '8.5"',
      offset: '+38mm',
      boltPattern: '5x112',
      centerBore: '66.6mm',
      weight: '20.1 lbs',
      finish: 'Machined Silver'
    }),
    inventoryQty: 14,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-blade-19x9-5',
    name: 'KG1 Forged Blade 19x9.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Razor-sharp spoke design with wide profile for maximum grip and stance.',
    price: 1149.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '19"',
      width: '9.5"',
      offset: '+22mm',
      boltPattern: '5x120',
      centerBore: '72.6mm',
      weight: '24.3 lbs',
      finish: 'Matte Bronze'
    }),
    inventoryQty: 10,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-phoenix-20x9',
    name: 'KG1 Forged Phoenix 20x9',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Rising phoenix-inspired design with premium forged construction and stunning finish.',
    price: 1199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '20"',
      width: '9"',
      offset: '+35mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '26.7 lbs',
      finish: 'Gloss White'
    }),
    inventoryQty: 11,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-eclipse-18x10',
    name: 'KG1 Forged Eclipse 18x10',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Wide-body wheel with eclipse-inspired spoke pattern. Built for aggressive fitments.',
    price: 1049.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '10"',
      offset: '+15mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '23.9 lbs',
      finish: 'Satin Black'
    }),
    inventoryQty: 13,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-thunder-17x9',
    name: 'KG1 Forged Thunder 17x9',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Thunderous performance with lightweight forged construction. Perfect for track days.',
    price: 849.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '17"',
      width: '9"',
      offset: '+40mm',
      boltPattern: '5x100',
      centerBore: '57.1mm',
      weight: '18.5 lbs',
      finish: 'Machined Black'
    }),
    inventoryQty: 16,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-venom-19x10',
    name: 'KG1 Forged Venom 19x10',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Venomous styling with wide stance capability. Forged for maximum strength.',
    price: 1249.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '19"',
      width: '10"',
      offset: '+20mm',
      boltPattern: '5x120',
      centerBore: '72.6mm',
      weight: '25.8 lbs',
      finish: 'Candy Red'
    }),
    inventoryQty: 9,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-fusion-18x7-5',
    name: 'KG1 Forged Fusion 18x7.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Fusion of style and performance in a lightweight package. Ideal for daily driving.',
    price: 799.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '7.5"',
      offset: '+48mm',
      boltPattern: '5x112',
      centerBore: '66.6mm',
      weight: '18.2 lbs',
      finish: 'Hyper Silver'
    }),
    inventoryQty: 18,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-matrix-20x8-5',
    name: 'KG1 Forged Matrix 20x8.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Matrix-inspired geometric design with premium forged aluminum construction.',
    price: 1149.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '20"',
      width: '8.5"',
      offset: '+45mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '24.1 lbs',
      finish: 'Titanium Gray'
    }),
    inventoryQty: 12,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-rebel-17x8-5',
    name: 'KG1 Forged Rebel 17x8.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Rebellious design with aggressive stance. Built for those who dare to be different.',
    price: 899.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '17"',
      width: '8.5"',
      offset: '+35mm',
      boltPattern: '5x100',
      centerBore: '57.1mm',
      weight: '19.7 lbs',
      finish: 'Matte Gunmetal'
    }),
    inventoryQty: 15,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-cyclone-19x8',
    name: 'KG1 Forged Cyclone 19x8',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Cyclonic spoke pattern with aerodynamic efficiency. Forged for performance enthusiasts.',
    price: 999.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '19"',
      width: '8"',
      offset: '+50mm',
      boltPattern: '5x112',
      centerBore: '66.6mm',
      weight: '22.4 lbs',
      finish: 'Polished Silver'
    }),
    inventoryQty: 14,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-inferno-18x9-5',
    name: 'KG1 Forged Inferno 18x9.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Fiery design with wide profile for maximum performance. Forged aluminum construction.',
    price: 1099.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '9.5"',
      offset: '+25mm',
      boltPattern: '5x120',
      centerBore: '72.6mm',
      weight: '22.8 lbs',
      finish: 'Orange Accent'
    }),
    inventoryQty: 11,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-stealth-20x10-5',
    name: 'KG1 Forged Stealth 20x10.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Stealth-inspired design with maximum width for ultimate stance and grip.',
    price: 1399.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '20"',
      width: '10.5"',
      offset: '+15mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '28.9 lbs',
      finish: 'Flat Black'
    }),
    inventoryQty: 7,
    isFeatured: true,
  },
  {
    slug: 'kg1-forged-quantum-17x7',
    name: 'KG1 Forged Quantum 17x7',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Quantum physics-inspired design with lightweight construction for daily performance.',
    price: 699.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '17"',
      width: '7"',
      offset: '+52mm',
      boltPattern: '5x100',
      centerBore: '57.1mm',
      weight: '16.2 lbs',
      finish: 'Silver Machined'
    }),
    inventoryQty: 22,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-nexus-19x9',
    name: 'KG1 Forged Nexus 19x9',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Nexus of performance and style. Premium forged construction with modern aesthetics.',
    price: 1199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '19"',
      width: '9"',
      offset: '+30mm',
      boltPattern: '5x112',
      centerBore: '66.6mm',
      weight: '23.6 lbs',
      finish: 'Brushed Titanium'
    }),
    inventoryQty: 13,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-phantom-18x8',
    name: 'KG1 Forged Phantom 18x8',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Phantom-like elegance with subtle spoke design. Perfect balance of form and function.',
    price: 949.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '18"',
      width: '8"',
      offset: '+42mm',
      boltPattern: '5x114.3',
      centerBore: '67.1mm',
      weight: '20.5 lbs',
      finish: 'Charcoal Gray'
    }),
    inventoryQty: 16,
    isFeatured: false,
  },
  {
    slug: 'kg1-forged-apex-pro-20x9-5',
    name: 'KG1 Forged Apex Pro 20x9.5',
    brand: 'KG1 Forged',
    category: 'Wheels',
    description: 'Professional-grade Apex design with enhanced strength and premium finish options.',
    price: 1349.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      diameter: '20"',
      width: '9.5"',
      offset: '+28mm',
      boltPattern: '5x120',
      centerBore: '72.6mm',
      weight: '27.2 lbs',
      finish: 'Carbon Fiber Accent'
    }),
    inventoryQty: 8,
    isFeatured: true,
  },

  // Tires (20) - 10 Toyo + 10 Nitto
  {
    slug: 'toyo-proxes-r888r-225-45r17',
    name: 'Toyo Proxes R888R 225/45R17',
    brand: 'Toyo',
    category: 'Tires',
    description: 'DOT-compliant competition tire with exceptional dry grip and track performance.',
    price: 289.99,
    compareAtPrice: 329.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '225/45R17',
      sidewall: '45',
      diameter: '17"',
      width: '225mm',
      loadIndex: '94',
      speedRating: 'W',
      treadDepth: '6/32"',
      compound: 'Competition'
    }),
    inventoryQty: 20,
    isFeatured: true,
  },
  {
    slug: 'toyo-proxes-sport-255-35r19',
    name: 'Toyo Proxes Sport 255/35R19',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Ultra-high performance tire with superior handling and wet weather capability.',
    price: 349.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '255/35R19',
      sidewall: '35',
      diameter: '19"',
      width: '255mm',
      loadIndex: '96',
      speedRating: 'Y',
      treadDepth: '8/32"',
      compound: 'Silica Enhanced'
    }),
    inventoryQty: 16,
    isFeatured: false,
  },
  {
    slug: 'toyo-open-country-at3-285-70r17',
    name: 'Toyo Open Country A/T III 285/70R17',
    brand: 'Toyo',
    category: 'Tires',
    description: 'All-terrain tire with aggressive tread pattern for on and off-road performance.',
    price: 279.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '285/70R17',
      sidewall: '70',
      diameter: '17"',
      width: '285mm',
      loadIndex: '121',
      speedRating: 'S',
      treadDepth: '12/32"',
      compound: 'All-Terrain'
    }),
    inventoryQty: 14,
    isFeatured: true,
  },
  {
    slug: 'toyo-proxes-st3-305-40r22',
    name: 'Toyo Proxes S/T III 305/40R22',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Sport truck tire with aggressive styling and excellent on-road performance.',
    price: 429.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '305/40R22',
      sidewall: '40',
      diameter: '22"',
      width: '305mm',
      loadIndex: '114',
      speedRating: 'V',
      treadDepth: '10/32"',
      compound: 'Sport Truck'
    }),
    inventoryQty: 12,
    isFeatured: false,
  },
  {
    slug: 'toyo-observe-gsi6-225-60r16',
    name: 'Toyo Observe GSi-6 225/60R16',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Winter tire with advanced tread compound for superior snow and ice traction.',
    price: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '225/60R16',
      sidewall: '60',
      diameter: '16"',
      width: '225mm',
      loadIndex: '98',
      speedRating: 'H',
      treadDepth: '11/32"',
      compound: 'Winter'
    }),
    inventoryQty: 18,
    isFeatured: false,
  },
  {
    slug: 'toyo-proxes-ra1-245-40r18',
    name: 'Toyo Proxes RA1 245/40R18',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Racing tire with maximum grip for autocross and track day events.',
    price: 319.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '245/40R18',
      sidewall: '40',
      diameter: '18"',
      width: '245mm',
      loadIndex: '97',
      speedRating: 'W',
      treadDepth: '5/32"',
      compound: 'Racing'
    }),
    inventoryQty: 15,
    isFeatured: true,
  },
  {
    slug: 'toyo-open-country-mt-33x12-50r15',
    name: 'Toyo Open Country M/T 33x12.50R15',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Mud terrain tire with aggressive tread blocks for extreme off-road conditions.',
    price: 359.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '33x12.50R15',
      sidewall: '12.50',
      diameter: '15"',
      width: '33"',
      loadIndex: '108',
      speedRating: 'Q',
      treadDepth: '18/32"',
      compound: 'Mud Terrain'
    }),
    inventoryQty: 10,
    isFeatured: false,
  },
  {
    slug: 'toyo-extensa-hp2-215-55r17',
    name: 'Toyo Extensa HP II 215/55R17',
    brand: 'Toyo',
    category: 'Tires',
    description: 'High-performance all-season tire with excellent wet and dry traction.',
    price: 159.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '215/55R17',
      sidewall: '55',
      diameter: '17"',
      width: '215mm',
      loadIndex: '94',
      speedRating: 'V',
      treadDepth: '9/32"',
      compound: 'All-Season'
    }),
    inventoryQty: 25,
    isFeatured: false,
  },
  {
    slug: 'toyo-proxes-cl1-suv-235-55r18',
    name: 'Toyo Proxes CL1 SUV 235/55R18',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Crossover and SUV tire with comfort-focused design and long tread life.',
    price: 219.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '235/55R18',
      sidewall: '55',
      diameter: '18"',
      width: '235mm',
      loadIndex: '100',
      speedRating: 'V',
      treadDepth: '10/32"',
      compound: 'Touring'
    }),
    inventoryQty: 19,
    isFeatured: false,
  },
  {
    slug: 'toyo-versado-noir-225-50r17',
    name: 'Toyo Versado Noir 225/50R17',
    brand: 'Toyo',
    category: 'Tires',
    description: 'Premium touring tire with advanced noise reduction and comfort technology.',
    price: 189.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '225/50R17',
      sidewall: '50',
      diameter: '17"',
      width: '225mm',
      loadIndex: '94',
      speedRating: 'V',
      treadDepth: '10/32"',
      compound: 'Touring'
    }),
    inventoryQty: 21,
    isFeatured: false,
  },

  // Nitto Tires (10)
  {
    slug: 'nitto-nt555-g2-275-40r20',
    name: 'Nitto NT555 G2 275/40R20',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Ultra-high performance tire with exceptional dry grip and responsive handling.',
    price: 389.99,
    compareAtPrice: 439.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '275/40R20',
      sidewall: '40',
      diameter: '20"',
      width: '275mm',
      loadIndex: '106',
      speedRating: 'W',
      treadDepth: '8/32"',
      compound: 'UHP Summer'
    }),
    inventoryQty: 14,
    isFeatured: true,
  },
  {
    slug: 'nitto-ridge-grappler-285-75r16',
    name: 'Nitto Ridge Grappler 285/75R16',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Hybrid terrain tire combining the best of all-terrain and mud-terrain performance.',
    price: 329.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '285/75R16',
      sidewall: '75',
      diameter: '16"',
      width: '285mm',
      loadIndex: '126',
      speedRating: 'Q',
      treadDepth: '15/32"',
      compound: 'Hybrid Terrain'
    }),
    inventoryQty: 12,
    isFeatured: true,
  },
  {
    slug: 'nitto-nt420v-305-50r20',
    name: 'Nitto NT420V 305/50R20',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Performance SUV tire with aggressive tread pattern and excellent road manners.',
    price: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '305/50R20',
      sidewall: '50',
      diameter: '20"',
      width: '305mm',
      loadIndex: '120',
      speedRating: 'V',
      treadDepth: '11/32"',
      compound: 'Performance SUV'
    }),
    inventoryQty: 9,
    isFeatured: false,
  },
  {
    slug: 'nitto-trail-grappler-37x12-50r17',
    name: 'Nitto Trail Grappler M/T 37x12.50R17',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Extreme mud-terrain tire with massive tread blocks for ultimate off-road traction.',
    price: 529.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '37x12.50R17',
      sidewall: '12.50',
      diameter: '17"',
      width: '37"',
      loadIndex: '124',
      speedRating: 'Q',
      treadDepth: '20/32"',
      compound: 'Mud Terrain'
    }),
    inventoryQty: 8,
    isFeatured: true,
  },
  {
    slug: 'nitto-neo-gen-225-45r18',
    name: 'Nitto Neo Gen 225/45R18',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Sport performance tire with modern tread design and excellent wet performance.',
    price: 249.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '225/45R18',
      sidewall: '45',
      diameter: '18"',
      width: '225mm',
      loadIndex: '95',
      speedRating: 'W',
      treadDepth: '8/32"',
      compound: 'Sport Performance'
    }),
    inventoryQty: 17,
    isFeatured: false,
  },
  {
    slug: 'nitto-terra-grappler-g2-275-65r18',
    name: 'Nitto Terra Grappler G2 275/65R18',
    brand: 'Nitto',
    category: 'Tires',
    description: 'All-terrain tire with reinforced construction for light truck and SUV applications.',
    price: 299.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '275/65R18',
      sidewall: '65',
      diameter: '18"',
      width: '275mm',
      loadIndex: '116',
      speedRating: 'T',
      treadDepth: '13/32"',
      compound: 'All-Terrain'
    }),
    inventoryQty: 15,
    isFeatured: false,
  },
  {
    slug: 'nitto-nt05-255-35r18',
    name: 'Nitto NT05 255/35R18',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Competition-focused tire with maximum dry grip for track and autocross use.',
    price: 359.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '255/35R18',
      sidewall: '35',
      diameter: '18"',
      width: '255mm',
      loadIndex: '94',
      speedRating: 'W',
      treadDepth: '6/32"',
      compound: 'Competition'
    }),
    inventoryQty: 13,
    isFeatured: true,
  },
  {
    slug: 'nitto-dura-grappler-265-70r17',
    name: 'Nitto Dura Grappler 265/70R17',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Highway terrain tire with long tread life and comfortable ride quality.',
    price: 219.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '265/70R17',
      sidewall: '70',
      diameter: '17"',
      width: '265mm',
      loadIndex: '115',
      speedRating: 'T',
      treadDepth: '12/32"',
      compound: 'Highway Terrain'
    }),
    inventoryQty: 20,
    isFeatured: false,
  },
  {
    slug: 'nitto-invo-295-35r21',
    name: 'Nitto INVO 295/35R21',
    brand: 'Nitto',
    category: 'Tires',
    description: 'Ultra-high performance tire with asymmetric tread pattern for luxury sports cars.',
    price: 499.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '295/35R21',
      sidewall: '35',
      diameter: '21"',
      width: '295mm',
      loadIndex: '107',
      speedRating: 'Y',
      treadDepth: '8/32"',
      compound: 'UHP Luxury'
    }),
    inventoryQty: 7,
    isFeatured: true,
  },
  {
    slug: 'nitto-exo-grappler-285-70r17',
    name: 'Nitto Exo Grappler AWT 285/70R17',
    brand: 'Nitto',
    category: 'Tires',
    description: 'All-weather terrain tire with enhanced traction in snow and ice conditions.',
    price: 339.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      size: '285/70R17',
      sidewall: '70',
      diameter: '17"',
      width: '285mm',
      loadIndex: '121',
      speedRating: 'S',
      treadDepth: '14/32"',
      compound: 'All-Weather Terrain'
    }),
    inventoryQty: 11,
    isFeatured: false,
  },

  // Suspension (20) - Split between Rough Country, BDS Suspension, McGaughys
  // Rough Country (7)
  {
    slug: 'rough-country-4-inch-lift-kit-chevy-silverado',
    name: 'Rough Country 4" Lift Kit - Chevy Silverado 1500',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Complete 4-inch suspension lift kit with premium N3 shocks for Chevrolet Silverado 1500.',
    price: 899.99,
    compareAtPrice: 1199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '4 inches',
      fitment: '2014-2018 Chevrolet Silverado 1500',
      shockType: 'N3 Nitrogen Charged',
      springs: 'Coil Springs',
      warranty: 'Lifetime Replacement',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 12,
    isFeatured: true,
  },
  {
    slug: 'rough-country-6-inch-lift-kit-ford-f150',
    name: 'Rough Country 6" Lift Kit - Ford F-150',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Heavy-duty 6-inch lift kit with Vertex reservoir shocks for Ford F-150 trucks.',
    price: 1299.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '6 inches',
      fitment: '2015-2020 Ford F-150',
      shockType: 'Vertex Reservoir',
      springs: 'Leaf Springs',
      warranty: 'Lifetime Replacement',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 8,
    isFeatured: true,
  },
  {
    slug: 'rough-country-2-5-inch-leveling-kit-ram-1500',
    name: 'Rough Country 2.5" Leveling Kit - RAM 1500',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Front leveling kit to eliminate factory rake and accommodate larger tires.',
    price: 399.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '2.5 inches front',
      fitment: '2019-2023 RAM 1500',
      shockType: 'N3 Nitrogen Charged',
      springs: 'Coil Spacers',
      warranty: 'Lifetime Replacement',
      installation: 'Easy Difficulty'
    }),
    inventoryQty: 18,
    isFeatured: false,
  },
  {
    slug: 'rough-country-3-inch-lift-kit-jeep-wrangler-jk',
    name: 'Rough Country 3" Lift Kit - Jeep Wrangler JK',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Complete suspension lift with premium shocks for Jeep Wrangler JK models.',
    price: 749.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '3 inches',
      fitment: '2007-2018 Jeep Wrangler JK',
      shockType: 'N3 Nitrogen Charged',
      springs: 'Coil Springs',
      warranty: 'Lifetime Replacement',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 15,
    isFeatured: true,
  },
  {
    slug: 'rough-country-5-inch-lift-kit-toyota-tacoma',
    name: 'Rough Country 5" Lift Kit - Toyota Tacoma',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Aggressive 5-inch lift system for Toyota Tacoma with premium components.',
    price: 1099.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '5 inches',
      fitment: '2016-2023 Toyota Tacoma',
      shockType: 'Vertex Reservoir',
      springs: 'Coil Springs',
      warranty: 'Lifetime Replacement',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 10,
    isFeatured: false,
  },
  {
    slug: 'rough-country-lowering-kit-chevy-silverado',
    name: 'Rough Country 4/6 Lowering Kit - Chevy Silverado',
    brand: 'Rough Country',
    category: 'Suspension',
    description: '4-inch front, 6-inch rear lowering kit for aggressive stance and improved handling.',
    price: 649.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '-4/-6 inches',
      fitment: '2014-2018 Chevrolet Silverado 1500',
      shockType: 'N3 Nitrogen Charged',
      springs: 'Lowering Springs',
      warranty: 'Lifetime Replacement',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 14,
    isFeatured: false,
  },
  {
    slug: 'rough-country-sway-bar-links-jeep-wrangler',
    name: 'Rough Country Sway Bar Links - Jeep Wrangler JL',
    brand: 'Rough Country',
    category: 'Suspension',
    description: 'Heavy-duty sway bar links for improved articulation and off-road performance.',
    price: 149.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: 'Compatible with 2-6" lifts',
      fitment: '2018-2023 Jeep Wrangler JL',
      shockType: 'N/A',
      springs: 'N/A',
      warranty: 'Lifetime Replacement',
      installation: 'Easy Difficulty'
    }),
    inventoryQty: 25,
    isFeatured: false,
  },

  // BDS Suspension (7)
  {
    slug: 'bds-6-inch-lift-kit-ford-f250-super-duty',
    name: 'BDS 6" Lift Kit - Ford F-250 Super Duty',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Premium 6-inch lift system with Fox 2.0 shocks for Ford Super Duty trucks.',
    price: 1899.99,
    compareAtPrice: 2299.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '6 inches',
      fitment: '2017-2023 Ford F-250/F-350 Super Duty',
      shockType: 'Fox 2.0 Performance',
      springs: 'Coil Springs',
      warranty: 'No Limit Warranty',
      installation: 'Professional Recommended'
    }),
    inventoryQty: 6,
    isFeatured: true,
  },
  {
    slug: 'bds-4-inch-lift-kit-chevy-colorado',
    name: 'BDS 4" Lift Kit - Chevy Colorado/GMC Canyon',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Complete 4-inch suspension system with premium Fox shocks for mid-size trucks.',
    price: 1399.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '4 inches',
      fitment: '2015-2023 Chevrolet Colorado/GMC Canyon',
      shockType: 'Fox 2.0 IFP',
      springs: 'Coil Springs',
      warranty: 'No Limit Warranty',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 9,
    isFeatured: false,
  },
  {
    slug: 'bds-3-inch-lift-kit-jeep-wrangler-jl',
    name: 'BDS 3" Lift Kit - Jeep Wrangler JL',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Engineered suspension lift with Fox shocks for Jeep Wrangler JL models.',
    price: 1199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '3 inches',
      fitment: '2018-2023 Jeep Wrangler JL',
      shockType: 'Fox 2.0 Performance',
      springs: 'Coil Springs',
      warranty: 'No Limit Warranty',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 11,
    isFeatured: true,
  },
  {
    slug: 'bds-2-inch-leveling-kit-gmc-sierra',
    name: 'BDS 2" Leveling Kit - GMC Sierra 1500',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Precision-engineered leveling kit with premium components for GMC Sierra.',
    price: 549.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '2 inches front',
      fitment: '2014-2018 GMC Sierra 1500',
      shockType: 'Fox 2.0 IFP',
      springs: 'Coil Spacers',
      warranty: 'No Limit Warranty',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 16,
    isFeatured: false,
  },
  {
    slug: 'bds-8-inch-lift-kit-ford-f150',
    name: 'BDS 8" Lift Kit - Ford F-150',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Extreme 8-inch lift system with Fox 2.5 reservoir shocks for maximum capability.',
    price: 2499.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '8 inches',
      fitment: '2015-2020 Ford F-150',
      shockType: 'Fox 2.5 Reservoir',
      springs: 'Coil Springs',
      warranty: 'No Limit Warranty',
      installation: 'Professional Required'
    }),
    inventoryQty: 4,
    isFeatured: true,
  },
  {
    slug: 'bds-5-inch-lift-kit-ram-2500',
    name: 'BDS 5" Lift Kit - RAM 2500/3500',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Heavy-duty 5-inch lift for RAM HD trucks with Fox performance shocks.',
    price: 1699.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '5 inches',
      fitment: '2014-2023 RAM 2500/3500',
      shockType: 'Fox 2.0 Performance',
      springs: 'Leaf Springs',
      warranty: 'No Limit Warranty',
      installation: 'Professional Recommended'
    }),
    inventoryQty: 7,
    isFeatured: false,
  },
  {
    slug: 'bds-control-arms-toyota-4runner',
    name: 'BDS Upper Control Arms - Toyota 4Runner',
    brand: 'BDS Suspension',
    category: 'Suspension',
    description: 'Heavy-duty upper control arms with uniball joints for Toyota 4Runner.',
    price: 799.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: 'Compatible with 0-6" lifts',
      fitment: '2010-2023 Toyota 4Runner',
      shockType: 'N/A',
      springs: 'N/A',
      warranty: 'No Limit Warranty',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 13,
    isFeatured: false,
  },

  // McGaughys (6)
  {
    slug: 'mcgaughys-7-inch-lift-kit-chevy-silverado-2500hd',
    name: 'McGaughys 7" Lift Kit - Chevy Silverado 2500HD',
    brand: 'McGaughys',
    category: 'Suspension',
    description: 'Premium 7-inch lift system with Bilstein shocks for heavy-duty Silverado trucks.',
    price: 1799.99,
    compareAtPrice: 2199.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '7 inches',
      fitment: '2011-2019 Chevrolet Silverado 2500HD/3500HD',
      shockType: 'Bilstein 5100',
      springs: 'Leaf Springs',
      warranty: 'Limited Lifetime',
      installation: 'Professional Recommended'
    }),
    inventoryQty: 5,
    isFeatured: true,
  },
  {
    slug: 'mcgaughys-3-5-inch-lowering-kit-chevy-silverado',
    name: 'McGaughys 3/5 Lowering Kit - Chevy Silverado',
    brand: 'McGaughys',
    category: 'Suspension',
    description: '3-inch front, 5-inch rear lowering kit for aggressive stance and improved handling.',
    price: 899.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '-3/-5 inches',
      fitment: '2014-2018 Chevrolet Silverado 1500',
      shockType: 'Bilstein B8 Performance',
      springs: 'Lowering Springs',
      warranty: 'Limited Lifetime',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 12,
    isFeatured: true,
  },
  {
    slug: 'mcgaughys-2-inch-leveling-kit-ford-f150',
    name: 'McGaughys 2" Leveling Kit - Ford F-150',
    brand: 'McGaughys',
    category: 'Suspension',
    description: 'Precision leveling kit with premium components for Ford F-150 trucks.',
    price: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '2 inches front',
      fitment: '2015-2020 Ford F-150',
      shockType: 'Bilstein 5100',
      springs: 'Coil Spacers',
      warranty: 'Limited Lifetime',
      installation: 'Moderate Difficulty'
    }),
    inventoryQty: 19,
    isFeatured: false,
  },
  {
    slug: 'mcgaughys-6-inch-lift-kit-gmc-sierra-1500',
    name: 'McGaughys 6" Lift Kit - GMC Sierra 1500',
    brand: 'McGaughys',
    category: 'Suspension',
    description: 'Complete 6-inch suspension lift with premium Bilstein shocks for GMC Sierra.',
    price: 1499.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '6 inches',
      fitment: '2014-2018 GMC Sierra 1500',
      shockType: 'Bilstein 5100',
      springs: 'Coil Springs',
      warranty: 'Limited Lifetime',
      installation: 'Professional Recommended'
    }),
    inventoryQty: 8,
    isFeatured: false,
  },
  {
    slug: 'mcgaughys-4-6-lowering-kit-ram-1500',
    name: 'McGaughys 4/6 Lowering Kit - RAM 1500',
    brand: 'McGaughys',
    category: 'Suspension',
    description: '4-inch front, 6-inch rear lowering system for RAM 1500 trucks.',
    price: 1099.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '-4/-6 inches',
      fitment: '2019-2023 RAM 1500',
      shockType: 'Bilstein B8 Performance',
      springs: 'Lowering Springs',
      warranty: 'Limited Lifetime',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 10,
    isFeatured: true,
  },
  {
    slug: 'mcgaughys-spindles-chevy-tahoe',
    name: 'McGaughys Drop Spindles - Chevy Tahoe/Suburban',
    brand: 'McGaughys',
    category: 'Suspension',
    description: 'Precision-machined drop spindles for lowering Chevy Tahoe and Suburban.',
    price: 649.99,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    specs: JSON.stringify({
      liftHeight: '-2 inches',
      fitment: '2015-2020 Chevrolet Tahoe/Suburban',
      shockType: 'Compatible with OEM',
      springs: 'Drop Spindles',
      warranty: 'Limited Lifetime',
      installation: 'Advanced Difficulty'
    }),
    inventoryQty: 15,
    isFeatured: false,
  },
]

async function main() {
  console.log('Start seeding...')
  
  // Clear existing products
  await prisma.product.deleteMany({})
  
  // Insert all products
  for (const product of products) {
    await prisma.product.create({
      data: product,
    })
  }
  
  console.log(`Seeded ${products.length} products`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })

